
// const HOST = "/MYSIGN/";
// var paymenturl = "/PAYMENTSIMULATOR/getunitscalltesting";
// const HOST = "https://docuxecstage.finfotech.co.in/MYSIGN/";
// var paymenturl = "https://docuxecstage.finfotech.co.in/PAYMENTSIMULATOR/getunitscalltesting";
const HOST = "http://localhost:8090/MYSIGN/";
var paymenturl = "http://localhost:8095/PAYMENTSIMULATOR/getunitscalltesting";

const footerContent =
  "Copyright ©️ 2024 Integra Micro Systems Private Ltd. All Rights Reserved. Version : 1.9.26";

// const rupeeIcon = '\&#x20B9';
const rupeeSymbol = '\u20B9';

let URL = {
  appName: "DocuExec",
  register: HOST + "userRegister",
  regValidateOtp: HOST + "regValidateOtp",
  validateOtp: HOST + "validateOtp",
  login: HOST + "loginValidate",
  getOtp: HOST + "getOtp",
  getFlags: HOST + "getFlags",
  getTermsAndConditions: HOST + "getTermsAndConditions",
  getSignedDoc: HOST + "getSignedDoc",
  getSignedDocV2: HOST + "getSignedDocV2",
  download: HOST + "download",
  getWalletInfo: HOST + "getWalletDetails",
  getUnitsHistory: HOST + "getUnitsHistory",
  getPaymentHistory: HOST + "getPaymentHistory",
  getProfileDetails: HOST + "getProfileDetails",
  changePassword: HOST + "changePassword",
  editProfile: HOST + "editProfile",
  getOtpForgotPassword: HOST + "getOtpForgotPassword",
  forgotPassword: HOST + "forgotPassword",
  getQR: HOST + "getQR",
  getPaymentStatus: HOST + "getPaymentStatus",
  logOut: HOST + "logOut",
  getRequiredUnits: HOST + "getRequiredUnits",
  getServices: HOST + "getServices",
  updateServices: HOST + "updateServices",
  getPaymentReports: HOST + "getPaymentReports",
  geteSignReports: HOST + "geteSignReports",
  getUsersReports: HOST + "getUsersReports",
  consenteSign: HOST + "consenteSign",
  getSummaryPDF: HOST + "getSummaryPDF",
  mpsGetGuestAccess: HOST + "mpsGetGuestAccess",
  mpsCreateJobs: HOST + "mpsCreateJobs",
  mpsCreateJobsV2: HOST + "mpsCreateJobsV2",
  getInboxDocDetails: HOST + "getInboxDocDetails",
  downloadStoredFile: HOST + "inbox/downloadFile",
  deleteStoredFile: HOST + "inbox/deleteFile",
  cancelSigningJob: HOST + "inbox/cancelJob",
  selfTokenSign: HOST + "selfTokenSign",
  viewStoredFile: HOST + "inbox/viewFile",
  downloadClientProgram: HOST + "downloadClientProgram",
  generateOTP: HOST + "generateOTP",
  resendEsignOtp: HOST + "resendEsignOtp",
  generatedscaccesscode: HOST + "generatedscaccesscode",
  unlockdscdocument: HOST + "unlockdscdocument",
  getSubscriptionLists: HOST + "getSubscriptionLists",
  subscribedPlanDetails: HOST + "subscribedPlanDetails",
  checkinQueuePlan: HOST + "checkSubscriptionDetails",
  viewConsentFile: HOST + "viewConsentFile",
  sendReminder: HOST + "inbox/sendReminder",
  paymenturl: paymenturl,
  getOtpforVerification: HOST + "getOtpforVerification",
  footerContent: footerContent,
  getOtpforEditProfileVerftn: HOST + "getOtpforEditProfileVerftn",
  viewSignedFile: HOST + "viewSignedFile",
  getstoredFilefrmTempDetails: HOST + "getstoredFilefrmTempDetails",
  downloadfromtemp: HOST + "downloadfromtemp",
  digiLocker: HOST + "digilocker/makedigilockercall",
  KYCDetails: HOST + "getUserAadharDetails",
  BulkRegistration: HOST + "bulkRegistration",
  generateOtpforMobAccess: HOST + "generateOtpforMobAccess",
  withdrawMoney: HOST + "withdrawMoney",
  getBankDetails: HOST + "getBankDetails",
  downloadSignCmpltd: HOST + "downloadSignCmpltd",
  DeleteUser: HOST + "deleteUserAccount",
  getEmailTemplateValidation: HOST + "getEmailTemplateValidation",
  sendEmail: HOST + "emailDocument",
  getCaptchaCode: HOST + "getCaptchaCode",
  mpsGetGuestAccessV2: HOST + "mpsGetGuestAccessV2",
  getSignerComments: HOST + "getSignerComments",
  getrevenueReports: HOST + "getrevenueReports",
  getSignCoordinateDetails: HOST + "getSignCoordinateDetails",
  getTemplateList: HOST + "getTemplateList",
  generatePDFfromTemplate: HOST + "generatePDFfromTemplate",
  getTemplateInputs: HOST + "getTemplateInputs",
  addHtmlTempAndFormDetail: HOST + "insertIntoTempmasterp",
  getTemplateToBeApproved: HOST + "getTemToBeApproved",
  getTempAndFieldDetail: HOST + "getTempAndFieldDetail",
  insertHtmlTempAndFormDetails: HOST + "insertHtmlTempAndFormDetails",
  // getGroupFormTempGroup: HOST + "getGroupFormTempGroup",
  getTemplateApplnList: HOST + "getTemplateApplnList",
  updateTemplate: HOST + "updateTemplate",
  getTemplateListForAdmin: HOST + "gettemplatelistforadmin",
  saveTemplateDrafts: HOST + "saveTemplateDrafts",
  getEachTempDraftDetails: HOST + "getEachTempDraftDetails",
  getDraftTemplates: HOST + "getDraftTemplates",
  deleteTempDraft: HOST + "deleteTempDraft",
  dbsUAT: "https://ilpuat.finfotech.co.in/esc/test/dbs/ipayments",
  getTempForCsv: HOST + "getTempDetForCsv",
  getTempDetForMultiCsv: HOST + "getTempDetForMultiCsv",
  getTempsForThatGroupCode: HOST + "getTempsForThatGroupCode",
  getValidationKeys: HOST + "getValidationKeys",
  getRejectedTempData: HOST + "getUploadedTempList",
  deleteRejectedTemp: HOST + "deleteRejectedTemp",
  tempdataForEdit: HOST + "tempdataForEditAndApprove",
  getTemplateGrps: HOST + "getTemplateGrps",
  getAllTemplateGrps: HOST + "getTemplateGrps",
  getUserDetails: HOST + "getUserDetails",
  viewAddedTemplateUsers: HOST + "viewTemplateUsers",
  addTemplateUsers: HOST + "addTemplateUsers",
  removeTemplateUsers: HOST + "removeTemplateUsers",
  getCorpDetails: HOST + "getCorpDetails",
  modifygrpAdmin: HOST + "modifygrpAdmin",
  createTemplateGrp: HOST + "createTemplateGrp",
  getVoucherCodes: HOST + "getVoucherCodes",
  getVoucherInfo: HOST + "getVoucherInfo",
  getVoucherUsageDetails: HOST + "getVoucherUsageDetails",
  getVoucherSummary: HOST + "getVoucherSummary",
  subscribeVoucher: HOST + "subscribeVoucher",
  rupeeSymbol: rupeeSymbol,
  getCustomFields: HOST + "getCustomFields",
  updateCustomFields: HOST + "updateCustomFields",
  corpListAndSubGrp: HOST + "corpListAndSubGrp",
  getCorpMemberRequests: HOST + "getCorpMemberRequests",
  approveCorpMemberRequests: HOST + "approveCorpMemberRequests",
  addCorpMember: HOST + "addCorpMember",
  checkVoucherCodeAvailability: HOST+"checkUsrDefinedVchrCode",
  declineSigning: HOST+ "declineSigning",
};

module.exports = { URL };
